# Generated by Django 3.2.3 on 2021-05-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('02', 'Femenino'), ('01', 'Masculino'), ('00', 'No binario')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
