# Generated by Django 3.2.3 on 2021-06-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdg', '0002_auto_20210531_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(choices=[('1', 'Ama de casa'), ('2', 'Changarin'), ('3', 'Estudiante'), ('4', 'Inactivo'), ('5', 'Jubilado/Pensionado'), ('6', 'Patrón o empleador'), ('7', 'Servicio doméstico'), ('8', 'Trabajo voluntario'), ('9', 'Cuenta propia'), ('10', 'Cuidado doméstico sin remuneración'), ('11', 'Desocupado'), ('12', 'Economía popular/asociativo'), ('13', 'Empleado de un sector privado')], max_length=20)),
                ('condicion_laboral', models.CharField(choices=[('1', 'Formal'), ('2', 'Informal')], max_length=20)),
                ('frecuencia_laboral', models.CharField(choices=[('1', 'Permanente'), ('2', 'Esporádico'), ('3', 'Temporario')], max_length=20)),
                ('ingreso', models.FloatField(blank=True, default=None, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdg.solicitante')),
            ],
        ),
    ]
