# Generated by Django 3.2.3 on 2021-06-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdg', '0003_ocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_cronica', models.CharField(max_length=2)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdg.solicitante')),
            ],
        ),
    ]
