# Generated by Django 3.2.3 on 2021-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdg', '0004_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='cuil',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='dni',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='estadoCivil',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='fechaNacimiento',
            field=models.DateField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='genero',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='nacionalidad',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='tipoDeDocumento',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='condicion_laboral',
            field=models.CharField(choices=[('1', 'Formal'), ('2', 'Informal')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='frecuencia_laboral',
            field=models.CharField(choices=[('1', 'Permanente'), ('2', 'Esporádico'), ('3', 'Temporario')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='ocupacion',
            field=models.CharField(choices=[('1', 'Ama de casa'), ('2', 'Changarin'), ('3', 'Estudiante'), ('4', 'Inactivo'), ('5', 'Jubilado/Pensionado'), ('6', 'Patrón o empleador'), ('7', 'Servicio doméstico'), ('8', 'Trabajo voluntario'), ('9', 'Cuenta propia'), ('10', 'Cuidado doméstico sin remuneración'), ('11', 'Desocupado'), ('12', 'Economía popular/asociativo'), ('13', 'Empleado de un sector privado')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='salud',
            name='enfermedad_cronica',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='nombres',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='sexo',
            field=models.CharField(choices=[('02', 'Femenino'), ('01', 'Masculino'), ('00', 'No binario')], default=None, max_length=2),
        ),
    ]
