# Generated by Django 3.2.3 on 2021-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdg', '0005_auto_20210601_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='estadoCivil',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
